import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import "./globals.css";

export const metadata = {
  title: "Game of Life",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body>
          <Theme>{children}</Theme>
        </body>
    </html>
  );
}
